# Lab 1

In [16]:
import torch
import numpy as np

### Q1

In [17]:
x = torch.arange(12)
print("Original Tensor:")
print(x)

reshaped_x = x.reshape(3, 4) 
print("\nReshaped Tensor:")
print(reshaped_x)

Original Tensor:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Reshaped Tensor:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [57]:
view = x.view(3, 4)
print("Viewed Tensor:")
print(view)

Viewed Tensor:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [56]:
y = torch.ones(12)
stack = torch.stack((x, y), dim=0)
print("Stacked Tensor:")
print(stack)

Stacked Tensor:
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])


In [58]:
z = torch.ones(1, 3, 1)
print("Tensor with extra dimensions:")
print(z)

squeez = z.squeeze()
print("\nSqueezed Tensor:")
print(squeez)

Tensor with extra dimensions:
tensor([[[1.],
         [1.],
         [1.]]])

Squeezed Tensor:
tensor([1., 1., 1.])


In [59]:
unsqueeze = z.unsqueeze(0)
print("Unsqueezed Tensor:")
print(unsqueeze)

Unsqueezed Tensor:
tensor([[[[1.],
          [1.],
          [1.]]]])


### Q2

In [22]:
tensor = torch.randn(3, 1)
print("Original tensor:")
print(tensor)

permuted_tensor = tensor.permute(1, 0)
print("\nPermuted tensor (dim reordered to (1, 3)):")
print(permuted_tensor)

Original tensor:
tensor([[-0.5684],
        [-0.5562],
        [ 0.6695]])

Permuted tensor (dim reordered to (1, 3)):
tensor([[-0.5684, -0.5562,  0.6695]])


### Q3

#### Integer Indexing

In [61]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Tensor:")
print(tensor)
element = tensor[0, 1]
print("\nElement at (0, 1):", element)

Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Element at (0, 1): tensor(2)


#### Slicing

In [60]:
sliced = tensor[1:3, [0, 2]]
print("\nRows 1-2, Columns 0 and 2:")
print(sliced)


Rows 1-2, Columns 0 and 2:
tensor([[4, 6]])


#### Boolean  Indexing

In [62]:
mask = tensor > 5
filtered_tensor = tensor[mask]
print("\nElements greater than 5:")
print(filtered_tensor)


Elements greater than 5:
tensor([6, 7, 8, 9])


#### Advanced Indexing

In [63]:
tensor_3d = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                          [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

ind = tensor_3d[:, ..., 1]
print("\nAll matrices, column 1:")
print(ind)


All matrices, column 1:
tensor([[ 2,  5,  8],
        [11, 14, 17]])


### Q4

In [27]:
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])

tensor = torch.from_numpy(numpy_array)
print("NumPy array converted to PyTorch tensor:")
print(tensor)

numpy_array_back = tensor.numpy()
print("\nPyTorch tensor converted back to NumPy array:")
print(numpy_array_back)

NumPy array converted to PyTorch tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

PyTorch tensor converted back to NumPy array:
[[1 2 3]
 [4 5 6]]


### Q5

In [64]:
rand = torch.randn(7, 7)

print(rand)

tensor([[ 0.1984,  0.7821,  1.0391, -0.7245, -0.8489, -1.2169, -0.0810],
        [ 1.3615, -2.0615,  0.6741, -1.3233, -1.3598, -0.8667, -0.5640],
        [-2.0565, -0.3567,  0.9571, -0.6619, -0.8285, -0.6057, -0.1354],
        [ 0.7471,  0.6118,  1.8678, -0.2616, -0.2501,  0.5011,  0.2600],
        [-1.6370,  0.1577,  0.3957, -1.3677, -2.9662, -1.7178, -0.5824],
        [-0.6153,  1.5496,  0.5989, -0.6377, -2.2858, -0.3677, -0.3866],
        [-1.0370,  0.5920, -0.7557,  0.3917,  0.7470,  1.3798,  1.2877]])


### Q6

In [44]:
tensor_7x7 = torch.randn(7, 7)

tensor_1x7 = torch.randn(1, 7)

r = torch.matmul(tensor_7x7, tensor_1x7.T)

print("Product of matrix multiplication:")
print(r)

Product of matrix multiplication:
tensor([[ 0.8861],
        [ 0.1927],
        [-1.8275],
        [-2.0454],
        [-2.4822],
        [-1.8849],
        [-5.4286]])


### Q7

In [45]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

tensor1 = torch.randn(2, 3)
tensor2 = torch.randn(2, 3)

tensor1 = tensor1.to(device)
tensor2 = tensor2.to(device)

print("Tensor 1 on:", tensor1.device)
print(tensor1)
print("\nTensor 2 on:", tensor2.device)
print(tensor2)

Tensor 1 on: cuda:0
tensor([[ 1.1173, -2.5684, -1.3766],
        [-0.8294,  0.2219, -0.5452]], device='cuda:0')

Tensor 2 on: cuda:0
tensor([[ 0.4458, -0.1277, -0.3025],
        [ 1.8625,  0.9942, -0.3910]], device='cuda:0')


### Q8

In [46]:
r = torch.matmul(tensor1, tensor2.T)

print("Product of matrix multiplication:")
print(r)

Product of matrix multiplication:
tensor([[ 1.2426,  0.0658],
        [-0.2332, -1.1111]], device='cuda:0')


### Q9

In [67]:
maxx = torch.max(r)
minn = torch.min(r)

print(f"Max value in Result: {maxx}")
print(f"Min value in Result: {minn}")

Max value in Result: 1.242630124092102
Min value in Result: -1.111060619354248


### Q10

In [68]:
maxx = torch.argmax(r)
minn = torch.argmin(r)

print(f"Max value in Result: {maxx}")
print(f"Min value in Result: {minn}")

Max value in Result: 0
Min value in Result: 3


### Q11

In [69]:
torch.manual_seed(7)

t1 = torch.randn(1, 1, 1, 10)

t2 = tensor1.squeeze()

print("First tensor (shape (1, 1, 1, 10)):")
print(t1)
print(f"Shape of the first tensor: {t1.shape}\n")

print("\nSecond tensor after squeezing (shape (10)):")
print(t2)
print(f"Shape of the second tensor: {t2.shape}")

First tensor (shape (1, 1, 1, 10)):
tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]])
Shape of the first tensor: torch.Size([1, 1, 1, 10])


Second tensor after squeezing (shape (10)):
tensor([[ 1.1173, -2.5684, -1.3766],
        [-0.8294,  0.2219, -0.5452]], device='cuda:0')
Shape of the second tensor: torch.Size([2, 3])
